apiVersion: v1
kind: Service
metadata:
  name: mainflow
  namespace: dev
  labels:
    app.kubernetes.io/name: mainflow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mainflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000